<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Calculator</title>
  <style>
    input[type="text"], input[type="button"] {
      width: 50px;
      height: 50px;
      font-size: 20px;
      margin: 5px;
    }
  </style>
</head>
<body>
  <table>
    <tr>
      <td colspan="4"><input type="text" id="result" readonly></td>
    </tr>
    <tr>
      <td><input type="button" value="7" onclick="appendToResult('7')"></td>
      <td><input type="button" value="8" onclick="appendToResult('8')"></td>
      <td><input type="button" value="9" onclick="appendToResult('9')"></td>
      <td><input type="button" value="/" onclick="appendToResult('/')"></td>
    </tr>
    <tr>
      <td><input type="button" value="4" onclick="appendToResult('4')"></td>
      <td><input type="button" value="5" onclick="appendToResult('5')"></td>
      <td><input type="button" value="6" onclick="appendToResult('6')"></td>
      <td><input type="button" value="-" onclick="appendToResult('-')"></td>
    </tr>
    <tr>
      <td><input type="button" value="1" onclick="appendToResult('1')"></td>
      <td><input type="button" value="2" onclick="appendToResult('2')"></td>
      <td><input type="button" value="3" onclick="appendToResult('3')"></td>
      <td><input type="button" value="+" onclick="appendToResult('+')"></td>
    </tr>
    <tr>
      <td><input type="button" value="0" onclick="appendToResult('0')"></td>
      <td><input type="button" value="." onclick="appendToResult('.')"></
      
